name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build-container:
    name: build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Build and push to Docker Hub
        uses: docker/docker-push-action@v2
        with:
          context: .
          push: true
          tags: nicocab3/docker-work:latest, nicocab3/docker-work:${{ github.run_number }} 
